# app.yaml file for tutorial application
application: retweeted
version: 1
runtime: python
api_version: 1
handlers:
- url: /media
  static_dir: static
- url: /.*
  script: retweeted.py

builtins:
- datastore_admin: on